const DRESSES_CONFIG = [
     {
    id: 1,
    name: 'Elegant Evening Gown',
    image: [],
    description: 'A stunning evening gown perfect for formal events and special occasions.',
    pricePerDay: '₹120',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Red', 'Black', 'Navy'],
    category: 'Evening Wear',
    availability: true,
    rating: 4,
  }, 
  {
    id: 2,
    name: 'Bridal Lehenga',
    image: [],
    description: 'Traditional bridal lehenga with intricate embroidery and rich fabrics.',
    pricePerDay: '₹450',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Red', 'Maroon', 'Pink','Brown'],
    category: 'Bridal',
    availability: true,
    rating: 5,
  },
  {
    id: 3,
    name: 'Casual Day Dress',
    image: [],
    description: 'Comfortable cotton dress for daytime outings and casual events.',
    pricePerDay: '₹25',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Yellow', 'Blue', 'White'],
    category: 'Casual',
    availability: true,
    rating: 3.8,
  },
  {
    id: 4,
    name: 'Cocktail Dress',
    image:[],
    description: 'Short and chic cocktail dress suitable for parties and nights out.',
    pricePerDay: '₹60',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Emerald', 'Burgundy'],
    category: 'Party Wear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 5,
    name: 'Bohemian Maxi Dress',
    image: [],
    description: 'Flowy boho maxi with floral prints and comfortable fit.',
    pricePerDay: '₹35',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Olive', 'Rust', 'Cream'],
    category: 'Casual',
    availability: true,
    rating: 4.1,
  },
  {
    id: 6,
    name: 'Satin Slip Dress',
    image:[],
    description: 'Smooth satin slip dress with a minimalist silhouette.',
    pricePerDay: '₹55',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Champagne', 'Black', 'Blush'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.4,
  },
  {
    id: 7,
    name: 'Mermaid Bridal Gown',
    image: [],
    description: 'Fitted mermaid bridal gown with lace overlay and train.',
    pricePerDay: '₹600',
    sizesAvailable: ['S', 'M', 'L', 'XL', 'XXL'],
    colorsAvailable: ['Ivory', 'White'],
    category: 'Bridal',
    availability: false,
    rating: 4.9,
  },
  {
    id: 8,
    name: 'Vintage Tea Dress',
    image:[],
    description: 'Retro-inspired tea dress with a fitted waist and flared skirt.',
    pricePerDay: '₹40',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Navy', 'Polka Dot', 'Green'],
    category: 'Vintage',
    availability: true,
    rating: 4.0,
  },
  {
    id: 9,
    name: 'Prom Ball Gown',
    image: [],
    description: 'Full-skirt ball gown perfect for prom and grand events.',
    pricePerDay: '₹220',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Pink', 'Royal Blue', 'Gold'],
    category: 'Prom',
    availability: true,
    rating: 4.6,
  },
  {
    id: 10,
    name: 'Sequin Mini Dress',
    image: [],
    description: 'Sparkling sequin mini dress for bold party looks.',
    pricePerDay: '₹75',
    sizesAvailable: ['XS', 'S', 'M'],
    colorsAvailable: ['Silver', 'Black'],
    category: 'Party Wear',
    availability: true,
    rating: 4.3,
  },
  {
    id: 11,
    name: 'Classic Little Black Dress',
    image: [],
    description: 'Timeless little black dress that flatters most body types.',
    pricePerDay: '₹45',
    sizesAvailable: ['XS', 'S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.7,
  },
  {
    id: 12,
    name: 'Floral Sundress',
    image: [],
    description: 'Lightweight sundress with cheerful floral pattern.',
    pricePerDay: '₹28',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Pink', 'Yellow', 'White'],
    category: 'Casual',
    availability: true,
    rating: 3.9,
  },
  {
    id: 13,
    name: 'Structured Sheath Dress',
    image: [],
    description: 'Professional sheath dress ideal for business events and interviews.',
    pricePerDay: '₹50',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black', 'Gray', 'Navy'],
    category: 'Workwear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 14,
    name: 'Grecian Goddess Gown',
    image: [],
    description: 'Flowing Grecian-style gown with draped fabric and elegant silhouette.',
    pricePerDay: '₹135',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['White', 'Gold', 'Olive'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.5,
  },
  {
    id: 15,
    name: 'Engagement Saree',
    image: [],
    description: 'Embroidered saree suitable for engagement ceremonies and ethnic events.',
    pricePerDay: '₹180',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Peach', 'Red', 'Gold'],
    category: 'Ethnic',
    availability: true,
    rating: 4.8,
  },
  {
    id: 16,
    name: 'Denim Shirt Dress',
    image:[],
    description: 'Casual denim shirt dress with button-front and relaxed fit.',
    pricePerDay: '₹30',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Denim Blue'],
    category: 'Casual',
    availability: true,
    rating: 3.7,
  },
  {
    id: 17,
    name: 'High-Low Hem Dress',
    image: [],
    description: 'Stylish high-low hem dress that’s playful yet elegant.',
    pricePerDay: '₹48',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Coral', 'Teal', 'Black'],
    category: 'Party Wear',
    availability: true,
    rating: 4.0,
  },
  {
    id: 18,
    name: 'Velvet Wrap Dress',
    image: [],
    description: 'Luxurious velvet wrap dress that’s warm and sophisticated.',
    pricePerDay: '₹90',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Burgundy', 'Forest Green', 'Navy'],
    category: 'Evening Wear',
    availability: false,
    rating: 4.6,
  },
  {
    id: 19,
    name: 'Boho Embroidered Tunic',
    image: [],
    description: 'Relaxed embroidered tunic perfect for festivals and casual days.',
    pricePerDay: '₹22',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Cream', 'Turquoise', 'Rust'],
    category: 'Casual',
    availability: true,
    rating: 3.6,
  },
  {
    id: 20,
    name: 'Glamour Column Gown',
    image: [],
    description: 'Sleek column gown with minimalist charm and modern lines.',
    pricePerDay: '₹150',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Nude', 'Burgundy'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.7,
  },
  {
    id: 21,
    name: 'Ruffle Wrap Midi',
    image:[],
    description: 'Flattering wrap midi with playful ruffle details.',
    pricePerDay: '₹38',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Blue', 'Lavender', 'Red'],
    category: 'Casual',
    availability: true,
    rating: 4.0,
  },
  {
    id: 22,
    name: 'Traditional Anarkali',
    image: [],
    description: 'Floor-length Anarkali dress with heavy embellishments for weddings.',
    pricePerDay: '₹320',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Maroon', 'Gold', 'Ivory'],
    category: 'Ethnic',
    availability: true,
    rating: 4.8,
  },
  {
    id: 23,
    name: 'Shift Dress',
    image: [],
    description: 'Minimal shift dress that’s easy to wear and style for many occasions.',
    pricePerDay: '₹27',
    sizesAvailable: ['XS', 'S', 'M', 'L', 'XL'],
    colorsAvailable: ['Beige', 'Black', 'Blue'],
    category: 'Workwear',
    availability: true,
    rating: 3.9,
  },
  {
    id: 24,
    name: 'Cape Evening Gown',
    image:[],
    description: 'Dramatic evening gown with attached cape for a red-carpet look.',
    pricePerDay: '₹240',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Royal Blue'],
    category: 'Evening Wear',
    availability: false,
    rating: 4.9,
  },
  {
    id: 25,
    name: 'Garden Party Midi',
    image: [],
    description: 'Pretty midi dress ideal for garden parties and daytime weddings.',
    pricePerDay: '₹46',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Mint', 'Floral', 'Cream'],
    category: 'Casual',
    availability: true,
    rating: 4.1,
  },
  {
    id: 26,
    name: 'Glam Sequin Saree',
    image: [],
    description: 'Modern saree with sequin embellishments for evening ethnic looks.',
    pricePerDay: '₹200',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Gold', 'Silver'],
    category: 'Ethnic',
    availability: true,
    rating: 4.6,
  },
  {
    id: 27,
    name: 'Pleated Midi Skirt Dress',
    image: [],
    description: 'Pleated midi dress with a delicate waist tie for feminine styling.',
    pricePerDay: '₹34',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Rose', 'Navy', 'Olive'],
    category: 'Casual',
    availability: true,
    rating: 3.8,
  },
  {
    id: 28,
    name: 'Embellished Cape Saree',
    image: [],
    description: 'Designer cape saree with heavy beadwork and embroidered motifs.',
    pricePerDay: '₹500',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Ivory', 'Blush'],
    category: 'Bridal',
    availability: false,
    rating: 5,
  },
  {
    id: 29,
    name: 'Tuxedo Dress',
    image: [],
    description: 'Androgynous tuxedo-style dress with sharp tailoring and satin lapels.',
    pricePerDay: '₹95',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black', 'White'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 30,
    name: 'Silk Kaftan',
    image: [],
    description: 'Luxurious silk kaftan with hand-printed motifs, great for resort wear.',
    pricePerDay: '₹65',
    sizesAvailable: ['S', 'M', 'L', 'XL', 'XXL'],
    colorsAvailable: ['Turquoise', 'Coral', 'White'],
    category: 'Resort Wear',
    availability: true,
    rating: 4.3,
  }
];

export {DRESSES_CONFIG}
