// NOTE: these entries use Unsplash source image queries so the app immediately shows relevant images.
// You can replace any of these with local files in `public/images/` (use paths like '/images/your-file.jpg').
const DRESSES_CONFIG = [
  {
    id: 1,
    name: 'Elegant Evening Gown',
    image: ['https://cdn.jovani.com/wp-content/uploads/47219_GOLD_6684-534x800.jpg'],
    description: 'A stunning evening gown perfect for formal events and special occasions.',
    pricePerDay: '₹120/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Red', 'Black', 'Navy'],
    category: 'Evening Wear',
    availability: true,
    rating: 4,
  },
  {
    id: 2,
    name: 'Bridal Lehenga',
    image: ['https://cdn.shopaccino.com/nakhrali/products/302-14645481769833_m.jpg?v=613'],
    description: 'Traditional bridal lehenga with intricate embroidery and rich fabrics.',
    pricePerDay: '₹450/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Red', 'Maroon', 'Pink','Brown'],
    category: 'Bridal',
    availability: true,
    rating: 5,
  },
  {
    id: 3,
    name: 'Casual Day Dress',
    image: ['https://joeyclothing.com/cdn/shop/files/SAJ_3584.jpg?v=1738215209'],
    description: 'Comfortable cotton dress for daytime outings and casual events.',
    pricePerDay: '₹25/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Yellow', 'Blue', 'White'],
    category: 'Casual',
    availability: true,
    rating: 3.8,
  },
  {
    id: 4,
    name: 'Cocktail Dress',
    image: ['https://pc-ap.rtrcdn.com/productimages/front/1080x/1e/ONES39.jpg?auto=webp&optimize=medium&width=800'],
    description: 'Short and chic cocktail dress suitable for parties and nights out.',
    pricePerDay: '₹60/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Emerald', 'Burgundy'],
    category: 'Party Wear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 5,
    name: 'Bohemian Maxi Dress',
    image: ['https://bohemianloverunway.com.au/cdn/shop/files/LOOK11_JAASE_15thMay__027.jpg?crop=region&crop_height=2089&crop_left=0&crop_top=5&crop_width=1400&v=1749542825&width=1400'],
    description: 'Flowy boho maxi with floral prints and comfortable fit.',
    pricePerDay: '₹35/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Olive', 'Rust', 'Cream'],
    category: 'Casual',
    availability: true,
    rating: 4.1,
  },
  {
    id: 6,
    name: 'Satin Slip Dress',
    image: ['https://d3v4qpjzw4kz8j.cloudfront.net/optimise/UTSS19012Blush001.jpeg?height=440&quality=80&signature=f7c17b48cd2905217476ee49ee133a713995f2daf19c70d81490c1d886a42920&src0=uploads/product_image/photo/5df8ef2fdd232e256acf15e0/UTSS19012Blush001.jpg&version=20221026&watermark=false&width=275'],
    description: 'Smooth satin slip dress with a minimalist silhouette.',
    pricePerDay: '₹55/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Champagne', 'Black', 'Blush'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.4,
  },
  {
    id: 7,
    name: 'Mermaid Bridal Gown',
    image: ['https://m.media-amazon.com/images/I/51RQxBqdp2L.jpg'],
    description: 'Fitted mermaid bridal gown with lace overlay and train.',
    pricePerDay: '₹600/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL', 'XXL'],
    colorsAvailable: ['Ivory', 'White'],
    category: 'Bridal',
    availability: false,
    rating: 4.9,
  },
  {
    id: 8,
    name: 'Vintage Tea Dress',
    image: ['https://cdn.shopify.com/s/files/1/0378/5257/7932/products/11698.jpg?v=1589326407'],
    description: 'Retro-inspired tea dress with a fitted waist and flared skirt.',
    pricePerDay: '₹40/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Navy', 'Polka Dot', 'Green'],
    category: 'Vintage',
    availability: true,
    rating: 4.0,
  },
  {
    id: 9,
    name: 'Prom Ball Gown',
    image: ['https://www.showprettydress.com/cdn/shop/files/v-neck-sleeveless-crystal-beading-ball-gown-prom-dresses-showprettydress.jpg?v=1756737012&width=600'],
    description: 'Full-skirt ball gown perfect for prom and grand events.',
    pricePerDay: '₹220/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Pink', 'Royal Blue', 'Gold'],
    category: 'Prom',
    availability: true,
    rating: 4.6,
  },
  {
    id: 10,
    name: 'Sequin Mini Dress',
    image: ['https://www.motelrocks.com/cdn/shop/files/ZEYANA-UNLINED-MINI-DRESS-SEQUIN-GOLD-2_9ca1b1ab-731b-41b9-8c59-484e039ee9e9.jpg?crop=center&format=pjpg&v=1743585072&width=1024'],
    description: 'Sparkling sequin mini dress for bold party looks.',
    pricePerDay: '₹75/hour',
    sizesAvailable: ['XS', 'S', 'M'],
    colorsAvailable: ['Silver', 'Black'],
    category: 'Party Wear',
    availability: true,
    rating: 4.3,
  },
  {
    id: 11,
    name: 'Classic Little Black Dress',
    image: ['https://images.riverisland.com/image/upload/t_plp_portraitSmall/f_auto/q_auto/926882_main?_a=BATAV5eA0'],
    description: 'Timeless little black dress that flatters most body types.',
    pricePerDay: '₹45/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.7,
  },
  {
    id: 12,
    name: 'Floral Sundress',
    image: ['https://m.media-amazon.com/images/I/71npXhNx5HL.jpg'],
    description: 'Lightweight sundress with cheerful floral pattern.',
    pricePerDay: '₹28/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Pink', 'Yellow', 'White'],
    category: 'Casual',
    availability: true,
    rating: 3.9,
  },
  {
    id: 13,
    name: 'Structured Sheath Dress',
    image: ['https://anninc.scene7.com/is/image/AN/603954_7879?$488x601$'],
    description: 'Professional sheath dress ideal for business events and interviews.',
    pricePerDay: '₹50/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black', 'Gray', 'Navy'],
    category: 'Workwear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 14,
    name: 'Grecian Goddess Gown',
    image: ['https://i.etsystatic.com/18738767/r/il/b96cc0/6517517878/il_794xN.6517517878_gzag.jpg'],
    description: 'Flowing Grecian-style gown with draped fabric and elegant silhouette.',
    pricePerDay: '₹135/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['White', 'Gold', 'Olive'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.5,
  },
  {
    id: 15,
    name: 'Engagement Saree',
    image: ['https://binalpatel.in/cdn/shop/files/banner-01_a9cc3b0e-39b2-4d6b-867e-198ecff853f0_600x.jpg?v=1696928072'],
    description: 'Embroidered saree suitable for engagement ceremonies and ethnic events.',
    pricePerDay: '₹180/hour',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Peach', 'Red', 'Gold'],
    category: 'Ethnic',
    availability: true,
    rating: 4.8,
  },
  {
    id: 16,
    name: 'Denim Shirt Dress',
    image: ['https://assets.digitalcontent.marksandspencer.app/image/upload/w_2560,q_auto,f_auto/SD_10_T83_1030D_JQ_X_EC_0'],
    description: 'Casual denim shirt dress with button-front and relaxed fit.',
    pricePerDay: '₹30/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Denim Blue'],
    category: 'Casual',
    availability: true,
    rating: 3.7,
  },
  {
    id: 17,
    name: 'High-Low Hem Dress',
    image: ['https://m.media-amazon.com/images/I/51YT5QTPc-L.jpg'],
    description: 'Stylish high-low hem dress that’s playful yet elegant.',
    pricePerDay: '₹48/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Coral', 'Teal', 'Black'],
    category: 'Party Wear',
    availability: true,
    rating: 4.0,
  },
  {
    id: 18,
    name: 'Velvet Wrap Dress',
    image: ['https://i.etsystatic.com/5641614/c/1200/1200/0/45/il/563ac5/2040510188/il_600x600.2040510188_erdj.jpg'],
    description: 'Luxurious velvet wrap dress that’s warm and sophisticated.',
    pricePerDay: '₹90/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Burgundy', 'Forest Green', 'Navy'],
    category: 'Evening Wear',
    availability: false,
    rating: 4.6,
  },
  {
    id: 19,
    name: 'Boho Embroidered Tunic',
    image: ['https://m.media-amazon.com/images/I/71UF5E923rL.jpg'],
    description: 'Relaxed embroidered tunic perfect for festivals and casual days.',
    pricePerDay: '₹22/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Cream', 'Turquoise', 'Rust'],
    category: 'Casual',
    availability: true,
    rating: 3.6,
  },
  {
    id: 20,
    name: 'Glamour Column Gown',
    image: ['https://m.media-amazon.com/images/I/513BQen5G2L.jpg'],
    description: 'Sleek column gown with minimalist charm and modern lines.',
    pricePerDay: '₹150/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Nude', 'Burgundy'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.7,
  },
  {
    id: 21,
    name: 'Ruffle Wrap Midi',
    image: ['https://m.media-amazon.com/images/I/61msKj7I3FL.jpg'],
    description: 'Flattering wrap midi with playful ruffle details.',
    pricePerDay: '₹38/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Blue', 'Lavender', 'Red'],
    category: 'Casual',
    availability: true,
    rating: 4.0,
  },
  {
    id: 22,
    name: 'Traditional Anarkali',
    image: ['https://medias.utsavfashion.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/e/m/embroidered-art-silk-anarkali-suit-in-light-green-v1-kjc5511.jpg'],
    description: 'Floor-length Anarkali dress with heavy embellishments for weddings.',
    pricePerDay: '₹320/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Maroon', 'Gold', 'Ivory'],
    category: 'Ethnic',
    availability: true,
    rating: 4.8,
  },
  {
    id: 23,
    name: 'Shift Dress',
    image: ['https://m.media-amazon.com/images/I/613BhBQTB7L.jpg'],
    description: 'Minimal shift dress that’s easy to wear and style for many occasions.',
    pricePerDay: '₹27/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L', 'XL'],
    colorsAvailable: ['Beige', 'Black', 'Blue'],
    category: 'Workwear',
    availability: true,
    rating: 3.9,
  },
  {
    id: 24,
    name: 'Cape Evening Gown',
    image: ['https://m.media-amazon.com/images/I/71hQ1yuqaOL.jpg'],
    description: 'Dramatic evening gown with attached cape for a red-carpet look.',
    pricePerDay: '₹240/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Black', 'Royal Blue'],
    category: 'Evening Wear',
    availability: false,
    rating: 4.9,
  },
  {
    id: 25,
    name: 'Garden Party Midi',
    image: ['https://shophalehouse.com/cdn/shop/files/IMG_13762_1000x1334.jpg?v=1740065993'],
    description: 'Pretty midi dress ideal for garden parties and daytime weddings.',
    pricePerDay: '₹46/hour',
    sizesAvailable: ['S', 'M', 'L'],
    colorsAvailable: ['Mint', 'Floral', 'Cream'],
    category: 'Casual',
    availability: true,
    rating: 4.1,
  },
  {
    id: 26,
    name: 'Glam Sequin Saree',
    image: ['https://glamwiz.com/cdn/shop/files/1copy_1024x1024.webp?v=1759313473'],
    description: 'Modern saree with sequin embellishments for evening ethnic looks.',
    pricePerDay: '₹200/hour',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Gold', 'Silver'],
    category: 'Ethnic',
    availability: true,
    rating: 4.6,
  },
  {
    id: 27,
    name: 'Pleated Midi Skirt Dress',
    image: ['https://i.etsystatic.com/27168120/c/852/852/0/243/il/c6ec7f/2810694652/il_600x600.2810694652_m0fb.jpg'],
    description: 'Pleated midi dress with a delicate waist tie for feminine styling.',
    pricePerDay: '₹34/hour',
    sizesAvailable: ['XS', 'S', 'M', 'L'],
    colorsAvailable: ['Rose', 'Navy', 'Olive'],
    category: 'Casual',
    availability: true,
    rating: 3.8,
  },
  {
    id: 28,
    name: 'Embellished Cape Saree',
    image: ['https://taruntahiliani.com/cdn/shop/files/196-TT11JUN23959_800x.jpg?v=1739525198'],
    description: 'Designer cape saree with heavy beadwork and embroidered motifs.',
    pricePerDay: '₹500/hour',
    sizesAvailable: ['One Size'],
    colorsAvailable: ['Ivory', 'Blush'],
    category: 'Bridal',
    availability: false,
    rating: 5,
  },
  {
    id: 29,
    name: 'Tuxedo Dress',
    image: ['https://dqp736wsu6w3m.cloudfront.net/s3bucket/w1000/looks/2856/classic-navy-tuxedo-with-ivory-shirt-and-oversized-bow.jpg'],
    description: 'Androgynous tuxedo-style dress with sharp tailoring and satin lapels.',
    pricePerDay: '₹95/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL'],
    colorsAvailable: ['Black', 'White'],
    category: 'Evening Wear',
    availability: true,
    rating: 4.2,
  },
  {
    id: 30,
      name: 'Silk Kaftan',
    image: ['https://i.etsystatic.com/25051493/c/1281/1281/0/274/il/dfb0f1/4117217490/il_600x600.4117217490_a51s.jpg'],
    description: 'Luxurious silk kaftan with hand-printed motifs, great for resort wear.',
    pricePerDay: '₹65/hour',
    sizesAvailable: ['S', 'M', 'L', 'XL', 'XXL'],
    colorsAvailable: ['Turquoise', 'Coral', 'White'],
    category: 'Resort Wear',
    availability: true,
    rating: 4.3,
  }
];

export {DRESSES_CONFIG}

  